export type Language = "en" | "zh-CN";

export const LANGUAGE_KEY = "p5js-studio-language";

export function readStoredLanguage(): Language {
  return localStorage.getItem(LANGUAGE_KEY) === "zh-CN" ? "zh-CN" : "en";
}

export const text = {
  en: {
    home: "Home",
    searchPlaceholder: "Search sketches...",
    language: "Language",
    help: "Help",
    english: "English",
    chinese: "Chinese",
    openFolder: "Open Folder",
    openFolderTitle: "Open the sketches folder",
    newFolder: "New Folder",
    newFolderPrompt: "New folder name",
    renameFolder: "Rename Folder",
    renameFolderPrompt: "Rename folder",
    deleteEmptyFolder: "Delete empty folder",
    deleteEmptyFolderConfirm: (name: string) => `Delete empty folder "${name}"?`,
    deleteFailed: "Delete failed",
    deleteFolderFailed:
      "This folder is not empty. Move or delete everything inside it before deleting the folder.",
    deleteSketchFailed: "Could not delete this sketch. Please try again.",
    importZip: "Import ZIP",
    importZipTitle: "Import sketches from ZIP",
    exportZip: "Export ZIP",
    exportZipTitle: "Export all sketches to ZIP",
    newSketch: "New Sketch",
    newSketchPrompt: "New sketch name",
    uploadJs: "Upload .js",
    noSketchesHere: "No sketches here",
    emptyHint: "Create a sketch, create a folder,\nupload a .js file, or import a ZIP",
    edit: "Edit",
    move: "Move",
    moveFailed: "Move failed",
    duplicate: "Duplicate",
    duplicateFailed: "Duplicate failed",
    deleteSketch: "Delete Sketch",
    deleteSketchConfirm: (name: string) => `Delete "${name}"?`,
    moveSketch: (name: string) => `Move ${name}`,
    cancel: "Cancel",
    gallery: "Gallery",
    backToGallery: "Gallery",
    loadingEditor: "Loading editor…",
    saved: "Saved",
    notes: "Notes",
    addNotesPlaceholder: "Add notes, description, or links for this sketch...",
    folderNotes: "Folder Notes",
    addFolderNotesPlaceholder: "Add notes, goals, or reminders for this folder...",
    clickToRename: "Click to rename",
    format: "Format",
    formatted: "Formatted",
    formatTitle: "Format current file",
    run: "Run",
    save: "Save",
    decreaseFont: "Decrease editor font size",
    increaseFont: "Increase editor font size",
    resizeEditorPreview: "Resize editor and preview",
    addFile: "Add File",
    addFileTitle: "Add file",
    removeFileTitle: "Remove file",
    removeFileConfirm: (name: string) => `Remove "${name}" from this sketch?`,
    debugConsole: "Debug Console",
    hideDebugConsole: "Hide",
    showDebugConsole: "Show",
    debugLogs: "logs",
    debugLevelError: "error",
    debugLevelWarning: "warning",
    debugLevelLog: "log",
    copyLogs: "Copy",
    clear: "Clear",
    noLogs: "No logs yet",
    currentProjectCount: (count: string) => `Current projects: ${count}`,
    pressRun: "Press Run or Ctrl+Enter",
    zoomOutPreview: "Zoom out preview",
    resetPreviewZoom: "Reset preview zoom",
    zoomInPreview: "Zoom in preview",
    light: "Light",
    dark: "Dark",
    toggleTheme: "Toggle light and dark mode",
    helpTitle: "P5JS Studio Help",
    closeHelp: "Close help",
    helpGalleryTitle: "Gallery",
    helpGallery:
      "Use folders to organize sketches. A folder with meta.json is a sketch; other folders are categories. ZIP import and export keep the folder structure.",
    helpEditorTitle: "Editor",
    helpEditor:
      "Run executes the current sketch, Save writes all files and notes, Format formats the active file, and Add File can create extra JavaScript files for the same sketch.",
    helpAssetsTitle: "Assets",
    helpAssets:
      "Put images inside the sketch folder or the shared public folder. Relative paths such as images/pic1.png work from the sketch folder.",
    helpDebugTitle: "Debug",
    helpDebug:
      "The Debug Console shows console.log, warnings, syntax problems, and runtime errors. The editor also marks common p5 function typos.",
    helpPreviewTitle: "Preview",
    helpPreview:
      "Large canvases can be viewed with scrollbars or the preview zoom controls. Thumbnails are captured automatically after Run.",
    helpShortcutsTitle: "Shortcuts",
    shortcutRun: "Run",
    shortcutSave: "Save",
    shortcutFont: "Editor font size",
    shortcutFormat: "Format",
  },
  "zh-CN": {
    home: "主页",
    searchPlaceholder: "搜索草图...",
    language: "语言",
    help: "帮助",
    english: "英文",
    chinese: "中文",
    openFolder: "打开目录",
    openFolderTitle: "打开草图存储目录",
    newFolder: "新建文件夹",
    newFolderPrompt: "新建文件夹名称",
    renameFolder: "重命名",
    renameFolderPrompt: "重命名文件夹",
    deleteEmptyFolder: "删除空文件夹",
    deleteEmptyFolderConfirm: (name: string) => `删除空文件夹 "${name}"？`,
    deleteFailed: "删除失败",
    deleteFolderFailed: "这个文件夹不是空的。请先移动或删除里面的内容，再删除文件夹。",
    deleteSketchFailed: "无法删除这个草图，请再试一次。",
    importZip: "导入 ZIP",
    importZipTitle: "从 ZIP 导入草图",
    exportZip: "导出 ZIP",
    exportZipTitle: "将所有草图导出为 ZIP",
    newSketch: "新建草图",
    newSketchPrompt: "新建草图名称",
    uploadJs: "上传 .js",
    noSketchesHere: "这里还没有草图",
    emptyHint: "可以新建草图、新建文件夹，\n上传 .js 文件，或导入 ZIP",
    edit: "编辑",
    move: "移动",
    moveFailed: "移动失败",
    duplicate: "复制",
    duplicateFailed: "复制失败",
    deleteSketch: "删除草图",
    deleteSketchConfirm: (name: string) => `删除 "${name}"？`,
    moveSketch: (name: string) => `移动 ${name}`,
    cancel: "取消",
    gallery: "图库",
    backToGallery: "图库",
    loadingEditor: "正在加载编辑器…",
    saved: "已保存",
    notes: "笔记",
    addNotesPlaceholder: "添加笔记、说明或链接...",
    folderNotes: "文件夹笔记",
    addFolderNotesPlaceholder: "给这个文件夹添加说明、目标或提醒...",
    clickToRename: "点击重命名",
    format: "格式化",
    formatted: "已格式化",
    formatTitle: "格式化当前文件",
    run: "运行",
    save: "保存",
    decreaseFont: "减小编辑器字体",
    increaseFont: "增大编辑器字体",
    resizeEditorPreview: "调整代码区和预览区宽度",
    addFile: "添加文件",
    addFileTitle: "添加文件",
    removeFileTitle: "移除文件",
    removeFileConfirm: (name: string) => `从这个草图中移除 "${name}"？`,
    debugConsole: "调试控制台",
    hideDebugConsole: "隐藏",
    showDebugConsole: "显示",
    debugLogs: "条",
    debugLevelError: "错误",
    debugLevelWarning: "警告",
    debugLevelLog: "日志",
    copyLogs: "复制",
    clear: "清空",
    noLogs: "暂无日志",
    currentProjectCount: (count: string) => `当前项目数：${count}`,
    pressRun: "点击运行或按 Ctrl+Enter",
    zoomOutPreview: "缩小预览",
    resetPreviewZoom: "重置预览缩放",
    zoomInPreview: "放大预览",
    light: "亮色",
    dark: "暗色",
    toggleTheme: "切换亮色和暗色模式",
    helpTitle: "P5JS Studio 帮助",
    closeHelp: "关闭帮助",
    helpGalleryTitle: "图库",
    helpGallery:
      "用文件夹整理草图。包含 meta.json 的文件夹会被识别为草图，其他文件夹作为分类目录。ZIP 导入和导出会保留目录结构。",
    helpEditorTitle: "编辑器",
    helpEditor:
      "运行会执行当前草图，保存会写入所有文件和笔记，格式化会整理当前文件，添加文件可以给同一个草图增加额外 JavaScript 文件。",
    helpAssetsTitle: "资源",
    helpAssets:
      "图片可以放在草图文件夹或共享 public 文件夹。类似 images/pic1.png 的相对路径会从草图文件夹开始查找。",
    helpDebugTitle: "调试",
    helpDebug:
      "调试控制台会显示 console.log、警告、语法问题和运行时错误。编辑器也会标记常见 p5 函数拼写错误。",
    helpPreviewTitle: "预览",
    helpPreview:
      "大尺寸画布可以用滚动条查看，也可以用预览缩放控件缩放。缩略图会在运行后自动截取保存。",
    helpShortcutsTitle: "快捷键",
    shortcutRun: "运行",
    shortcutSave: "保存",
    shortcutFont: "编辑器字体大小",
    shortcutFormat: "格式化",
  },
} satisfies Record<Language, Record<string, string | ((value: string) => string)>>;

export type AppText = typeof text.en;
